---
# config cassandra
- name: edit cassandra.yaml
  template: 
    src: cassandra.yaml.j2
    dest: "{{ CASSANDRA_HOME + '/conf/cassandra.yaml' | replace('//','/') }}"

- name: edit cassandra-rack.properties
  template: 
    src: cassandra-rackdc.properties.j2 
    dest: "{{ CASSANDRA_HOME + '/conf/cassandra-rackdc.properties' | replace('//','/') }}"

- name: edit cassandra-env.sh
  template: 
    src: cassandra-env.sh.j2 
    dest: "{{ CASSANDRA_HOME + '/conf/cassandra-env.sh' | replace('//','/') }}"