---
# copy cassandra service
- name: copy cassandra.service
  template: src=cassandra.service.j2 dest=/etc/systemd/system/cassandra.service

- name: disable cassandra.service
  systemd: name=cassandra.service enabled=no daemon_reload=yes